# Check https://github.com/isa-group/botica/wiki/The-main-configuration-file for a complete guide.
broker:
  type: rabbitmq
  username: "username"
  password: "password"
  port: 5672

bots:
  my-bot:
    image: "my-bot-image"
    mount:
      - source: "path/to/host/file.extension"
        target: "path/to/container/file.extension"
      - source: "path/to/host/directory"
        target: "path/to/container/directory"
        createHostPath: true
    publish:
      key: "distributed_orders"
      order: "execute_order"
    lifecycle:
      type: proactive
      initialDelay: 60
      period: 60
    environment:
      - KEY=VALUE
    instances:
      bot-1: { }
      bot-2: { }
      bot-3:
        lifecycle: # overriding lifecycle configuration
          type: proactive
          initialDelay: 30
          period: 30
        environment: # these are combined with the already defined variables for the bot type
          - KEY2=VALUE2
      bot-4:
        environment:
          - KEY3=VALUE3

  my-other-bot:
    image: "my-other-bot-image"
    publish:
      key: "another_key"
      order: "execute_the_other_order"
    subscribe:
      - key: "distributed_orders"
        strategy: distributed # will be delivered to only one random instance
      - key: "broadcast_orders"
        strategy: broadcast # will be delivered to all instances
    lifecycle:
      type: reactive
      order: "execute_order"
    instances:
      bot-5: { }
      bot-6: { }
